### ISSUE TITLE
ADGuardHome

### ISSUE THREAD

**Issue by zzcabc** [QuentinHsu/Document-Page#4]
2021年4月18日第五版——更新DNS服务器，更新全部去广告规则
2021年4月10日第四版——重写去广告规则
2021年3月5日第三版——修复HalfLife的去广告规则国内无法获取，添加国外源
2021年3月4日第二版——添加遇到bug
2021年2月19日初步编写

# 目录

# [AdGuardHome](https://github.com/rufengsuixing/luci-app-adguardhome)

## 使用设置

**Comment by zzcabc** [comment]
在**设置** - **常规设置**
![配置1](https://user-images.githubusercontent.com/46120743/107867625-7f5ffe00-6eb7-11eb-9e7a-768a3df6c3d4.jpg)
根据自己喜好进行配置

在**设置** - **DNS设置** - **关键**
提供DNS，请合理使用，会更新，也欢迎大佬补充
```
国内DNS
114 DNS
114.114.114.114
114.114.115.115

Ali DNS
223.5.5.5
223.6.6.6
https://dns.alidns.com/dns-query
https://233.5.5.5/dns-query
https://233.6.6.6/dns-query

Baidu DNS
180.76.76.76

火绒
123.56.10.101
35.194.168.151
https://dns.flymc.cc/dns-query
https://dns.tw.flymc.cc/dns-query）


Tencent DNS
119.29.29.29
182.254.116.116
119.28.28.28
182.254.118.118
https://doh.pub/dns-query
https://dns.pub/dns-query

DNS派
101.226.4.6
218.30.118.6
https://doh.360.cn/dns-query

CNNIC DNS
1.2.4.8
210.2.4.8
https://dns.cfiec.net/dns-query

TUNA DNS
101.6.6.6

oneDNS
117.50.11.11
52.80.66.66

红鱼rubyfish DNS
https://rubyfish.cn/dns-query
https://dns.rubyfish.cn/dns-query

国外
Google DNS
8.8.8.8
8.8.4.4
https://dns.google/dns-query
https://dns.google/resolve

IBM Quad9
9.9.9.9
149.112.112.112
https://dns.quad9.net/dns-query (默认)
https://dns11.quad9.net/dns-query (安全&支持ECS)

OpenDNS	
208.67.222.222
208.67.220.220
https://doh.opendns.com/dns-query (默认)
https://doh.familyshield.opendns.com/dns-query (家庭保护)

Level3 DNS
4.2.2.1
4.2.2.2

韩国KT DNS
168.126.63.1
168.126.63.2

Cloudflare DNS
1.1.1.1
1.0.0.1
https://1.1.1.1/dns-query
https://1.0.0.1/dns-query
https://cloudflare-dns.com/dns-query

Free DNS	
37.235.1.174
37.235.1.177

DynDNS
216.146.35.35
216.146.36.36

Comodo DNS
8.26.56.26
8.20.247.20

Verisign DNS（威瑞信）
64.6.64.6
64.6.65.6

Yandex DNS
77.88.8.8
77.88.8.1

Freenom DNS（荷兰)
80.80.80.80
80.80.81.81

AdGuard DNS（测试版）
176.103.130.130（默认）
176.103.130.131（默认）
176.103.130.132(家庭保护）
176.103.130.134(家庭保护）
https://dns.adguard.com/dns-query (默认）
https://dns-family.adguard.com/dns-query (家庭保护）

Neustar UltraDNS
156.154.70.1
156.154.71.1
156.154.70.5
156.154.71.5

柬埔寨DNS
103.197.104.178
103.197.106.75
203.189.136.148

UCOM DNS日本东京
203.112.2.4

DNS.WATCH
84.200.69.80
84.200.70.40

SafeDNS
195.46.39.39
195.46.39.40

puntCAT DNS
109.69.8.51

UncensoredDNS
91.239.100.100
89.233.43.71

GreenTeamDNS
81.218.119.11
209.88.198.133

DNS.SB
185.222.222.222
185.184.222.222
https://doh.dns.sb/dns-query

Hurricane ElectricHE	
74.82.42.42
66.220.18.42

DNSReactor
104.236.210.29
45.55.155.25

CleanBrowsing DNS
185.228.168.9(Security Filter）
185.228.169.9(Security Filter）
185.228.168.10(Adult Filter）
185.228.169.11(Adult Filter）
185.228.168.168 (家庭保护）	
185.228.169.168 (家庭保护）
https://doh.cleanbrowsing.org/doh/family-filter/ (家庭保护）

PowerDNS
https://doh.powerdns.org

Worldlink DNS
202.79.32.33
202.79.32.34

日本IIJ DNS
https://public.dns.iij.jp/dns-query

Blahdns 日本节点
https://doh-jp.blahdns.com/dns-query
```
单一国内和国外DNS，请勿一起使用
![配置1](https://user-images.githubusercontent.com/46120743/107867688-eb426680-6eb7-11eb-8a42-d00f8964b0d2.jpg)
![配置2](https://user-images.githubusercontent.com/46120743/107867750-51c78480-6eb8-11eb-8501-f58f9a9a2c78.jpg)
![配置3](https://user-images.githubusercontent.com/46120743/107867786-aff46780-6eb8-11eb-9ff4-9c7ebf2540a9.jpg)
![配置4](https://user-images.githubusercontent.com/46120743/107867801-d4504400-6eb8-11eb-9af8-495fc9711ecd.jpg)

**Comment by zzcabc** [comment]
###  配置ssrplus或passwall或openclash请仅使用AdGuardHome的DNS功能，你去广告也没用，直连可以使用去广告，但是效果不怎么好，自己选择
**过滤器** - **DNS封锁清单**
```
HalfLife，规则合并自 EasylistChina、EasylistLite、CJX’sAnnoyance 合并规则（几乎每天更新)
https://gitee.com/halflife/list/raw/master/ad.txt

xinggsf，乘风广告过滤规则 + 视频过滤规则，乘风规则更新详情
https://gitee.com/xinggsf/Adblock-Rule/raw/master/rule.txt
https://gitee.com/xinggsf/Adblock-Rule/raw/master/mv.txt

cjx82630，cjxlist 国内备用地址
一、CJX’s Annoyance List (去自推列表)
https://gitee.com/cjx82630/cjxlist/raw/master/cjx-annoyance.txt
二、CJX’s uBlock list (uBlock 规则)
https://gitee.com/cjx82630/cjxlist/raw/master/cjx-ublock.txt

EasyList China : 国内网站广告过滤的主规则。
链接：https://easylist-downloads.adblockplus.org/easylistchina.txt
EasyPrivacy : EasyPrivacy 是隐私保护，不被跟踪。
链接：https://easylist-downloads.adblockplus.org/easyprivacy.txt
CJX’s Annoyance List : 过滤烦人的自我推广，并补充 EasyPrivacy 隐私规则。
链接：https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
I don’t care about cookies : 我不关心 Cookie 的问题，屏蔽网站的 cookies 相关的警告。
链接：https://www.i-dont-care-about-cookies.eu/abp/


EasyList
可从国际网页上删除大部分广告，包括不需要的框架，图像和对象
https://easylist-downloads.adblockplus.org/easylist.txt

EasyList China
EasyList的中文补充过滤器
https://easylist-downloads.adblockplus.org/easylistchina.txt

EasyPrivacy
可选的补充过滤器列表，该列表从网络删除了所有形式的跟踪，包括Web错误，跟踪脚本和信息收集器，从而保护您的个人数据
https://easylist-downloads.adblockplus.org/easyprivacy.txt

EasyList Cookie List
阻止cookie横幅，GDPR覆盖窗口和其他与隐私相关的通知
https://easylist-downloads.adblockplus.org/easylist-cookie.txt

Anti-AD
使用anti-AD能够屏蔽广告域名，能屏蔽电视盒子广告，屏蔽app内置广告，同时屏蔽了一些日志收集，大数据统计等涉及个人隐私信息的站点，能够保护个人隐私不被偷偷上传
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt
```

![配置1](https://user-images.githubusercontent.com/46120743/107867887-e54d8500-6eb9-11eb-9e16-9af7f9b86040.jpg)
添加就行

**Comment by zzcabc** [comment]
本人不对DNS服务器和广告过滤提供支持，如不满意请勿使用本人提供规则，配置ssrplus或passwall或openclash请设置为下游DNS，你流量都加密了，用个锤子的去广告，设置为下游我不会，如有人发现内容不妥，直接私聊开项目的人，我不经常看issue

**Comment by zzcabc** [comment]
AdGuardHome填写DNS要么全国内DNS要么全国外，AdGuardHome全部国外DNS在ssrplus直接填入127.0.0.1:5000这里演示用5000，即可，如果想分开请docker安装AdGuardHome设置方法依旧，本文不涉及docker故不讲解docker使用

**Comment by zzcabc** [comment]
## 具体设置
第一步 **<font color="red">打开仪表盘或输入路由器IP:3000</font>**

第二步 **<font color="red">输入设置的用户名和密码</font>**

第三步 **<font color="red">点击设置中的常规设置</font>** 

*<font color="blue">这里推荐默认，如果勾选下面会导致DNS查询速度大于100ms</font>*

![具体设置第一步](https://user-images.githubusercontent.com/46120743/110117090-5e723500-7df3-11eb-8a51-a403827e7373.png)


*<font color="blue">推荐24小时或7天，日志要占空间</font>*

![具体设置第二步](https://user-images.githubusercontent.com/46120743/110117100-616d2580-7df3-11eb-8456-79be600b8113.png)


*<font color="blue">同上</font>*

![具体设置第三步](https://user-images.githubusercontent.com/46120743/110117111-64681600-7df3-11eb-8c33-8f75ae864865.png)


第四步 **<font color="red">点击设置中的DNS设置</font>** 

*<font color="blue">上游DNS服务器中填几个国内或国外的DNS服务器，推荐单一性原则</font>*

*<font color="blue">下面推荐使用并行请求或最快的IP地址</font>*

![具体设置第四步](https://user-images.githubusercontent.com/46120743/110117133-68943380-7df3-11eb-9bc8-5454bfb8b6b1.png)


*<font color="blue">推荐2到3个以IP为主的DNS服务器可以选供应商提供的DNS服务器</font>*

![具体设置第五步](https://user-images.githubusercontent.com/46120743/110117141-6c27ba80-7df3-11eb-97f6-0a1962e51eeb.png)


*<font color="blue">树莓派4B性能完全可以不限制</font>*

*<font color="blue">可以勾选下面两个框</font>*

*<font color="blue">IPV6发育不完全，推挤禁用IPV6</font>*

![具体设置第六步](https://user-images.githubusercontent.com/46120743/110117159-71850500-7df3-11eb-81a9-19e81fead2d0.png)


*<font color="blue">缓存可以设置大一点</font>*

*<font color="blue">下面两个是缓存失效时间，最大建议3600，最小建议300</font>*

![具体设置第七步](https://user-images.githubusercontent.com/46120743/110117175-76e24f80-7df3-11eb-9d3b-6bae4befee0d.png)


第五步 **<font color="red">点击过滤器中的DNS封锁清单</font>**

*<font color="blue">添加就好了</font>*

![具体设置第八步](https://user-images.githubusercontent.com/46120743/110117185-79dd4000-7df3-11eb-90e1-4d592aac7f22.png)

**Comment by zzcabc** [comment]
## 具体设置
第一步 **<font color="red">打开仪表盘或输入路由器IP:3000</font>**

第二步 **<font color="red">输入设置的用户名和密码</font>**

第三步 **<font color="red">点击设置中的常规设置</font>** 

*<font color="blue">这里推荐默认，如果勾选下面会导致DNS查询速度大于100ms</font>*

![具体设置第一步](https://user-images.githubusercontent.com/46120743/110117090-5e723500-7df3-11eb-8a51-a403827e7373.png)


*<font color="blue">推荐24小时或7天，日志要占空间</font>*

![具体设置第二步](https://user-images.githubusercontent.com/46120743/110117100-616d2580-7df3-11eb-8456-79be600b8113.png)


*<font color="blue">同上</font>*

![具体设置第三步](https://user-images.githubusercontent.com/46120743/110117111-64681600-7df3-11eb-8c33-8f75ae864865.png)


第四步 **<font color="red">点击设置中的DNS设置</font>** 

*<font color="blue">上游DNS服务器中填几个国内或国外的DNS服务器，推荐单一性原则</font>*

*<font color="blue">下面推荐使用并行请求或最快的IP地址</font>*

![具体设置第四步](https://user-images.githubusercontent.com/46120743/110117133-68943380-7df3-11eb-9bc8-5454bfb8b6b1.png)


*<font color="blue">推荐2到3个以IP为主的DNS服务器可以选供应商提供的DNS服务器</font>*

![具体设置第五步](https://user-images.githubusercontent.com/46120743/110117141-6c27ba80-7df3-11eb-97f6-0a1962e51eeb.png)


*<font color="blue">树莓派4B性能完全可以不限制</font>*

*<font color="blue">可以勾选下面两个框</font>*

*<font color="blue">IPV6发育不完全，推挤禁用IPV6</font>*

![具体设置第六步](https://user-images.githubusercontent.com/46120743/110117159-71850500-7df3-11eb-81a9-19e81fead2d0.png)


*<font color="blue">缓存可以设置大一点</font>*

*<font color="blue">下面两个是缓存失效时间，最大建议3600，最小建议300</font>*

![具体设置第七步](https://user-images.githubusercontent.com/46120743/110117175-76e24f80-7df3-11eb-9d3b-6bae4befee0d.png)


第五步 **<font color="red">点击过滤器中的DNS封锁清单</font>**

*<font color="blue">添加就好了</font>*

![具体设置第八步](https://user-images.githubusercontent.com/46120743/110117185-79dd4000-7df3-11eb-90e1-4d592aac7f22.png)

**Comment by zzcabc** [comment]
## 使用设置

*如果你不使用任何出国插件，推荐使用**重定向53端口到AdGuardHome**或**使用53端口替换dnsmasq***

因为AdGuardHome不能分流DNS，所以如果使用出国插件，推荐配合docker版的AdGuardHome

插件重定向任意，docker版作为国外分流

![使用设置第一步](https://user-images.githubusercontent.com/46120743/110118506-6df27d80-7df5-11eb-892f-56bddda2f4a7.png)


使用5335端口时，SSR Plus+选择使用本机端口为5335的DNS服务

![使用设置第二步](https://user-images.githubusercontent.com/46120743/110118513-721e9b00-7df5-11eb-989a-cf216077b6a7.png)


使用PassWall，可以使用自定义DNS

![使用设置第三步](https://user-images.githubusercontent.com/46120743/110118524-75b22200-7df5-11eb-80b3-cd143f756ca7.png)

**Comment by CodeDreamfy** [comment]
在初始化ADGuardHome的时候提示80和53端口被占用，这种要怎么排查

**Comment by weitia** [comment]
666
